// <auto-generated />
using System;
using EntityFramework.Demo.TptModel.CodeFirst;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EntityFramework.Demo.TptModel.CodeFirst.Migrations
{
    [DbContext(typeof(TptDbContext))]
    partial class TptDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.0-rc1-32029")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EntityFramework.Demo.TptModel.CodeFirst.CustomerTpt", b =>
                {
                    b.Property<Guid>("Id");

                    b.Property<DateTime>("DateOfBirth");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("EntityFramework.Demo.TptModel.CodeFirst.EmployeeTpt", b =>
                {
                    b.Property<Guid>("Id");

                    b.Property<decimal>("Turnover");

                    b.HasKey("Id");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("EntityFramework.Demo.TptModel.CodeFirst.PersonTpt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.HasKey("Id");

                    b.ToTable("People");
                });

            modelBuilder.Entity("EntityFramework.Demo.TptModel.CodeFirst.CustomerTpt", b =>
                {
                    b.HasOne("EntityFramework.Demo.TptModel.CodeFirst.PersonTpt", "Person")
                        .WithMany()
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("EntityFramework.Demo.TptModel.CodeFirst.EmployeeTpt", b =>
                {
                    b.HasOne("EntityFramework.Demo.TptModel.CodeFirst.PersonTpt", "Person")
                        .WithMany()
                        .HasForeignKey("Id")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
